name: generate a gramine signature, which can be verified later

on:
  workflow_call:
  
permissions:
  attestations: write
  id-token: write
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write
    defaults:
      run:
        shell: bash
    steps:
      - name: create artifact
        run: echo notary-server.sig
      - name: upload it
        uses: actions/upload-artifact@v4
        with:
            path: notary-server.sig
      - name: get github to sign our measurement
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: notary-server.sig
